##########
#
# Compose-file for setting up all required (micro-)services for the project
#
# USED images from HUB:
# MariaDB:    https://hub.docker.com/_/mariadb/
# PHPMyAdmin: https://hub.docker.com/r/phpmyadmin/phpmyadmin/
# Adminer:    https://hub.docker.com/_/adminer/
#
##########

version: '2'

networks:
  app-network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.5.0.0/16
        gateway: 172.5.0.1

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    networks:
      app-network:
        ipv4_address: 172.5.0.2

    environment:
      MYSQL_ROOT_PASSWORD: datait2018!

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8081:80
    networks:
      app-network:
        ipv4_address: 172.5.0.3
    volumes:
      - /sessions

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8082:8080

  web:
    build: ./web/
    ports:
      - 8080:80
    networks:
      app-network:
        ipv4_address: 172.5.0.4
    volumes:
      - ./web/src/:/var/www/html/
